title: Zhiquan Shangguan's Homepage
#page-top-title: User Name
top-section-bg-text: Zhiquan Shangguan|上官知权
#home-subtitle: User Name&ensp;|&ensp;姓名
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
